module.exports = {
  base: '/notes/',
  title: 'Full-stack web development notes.',
  description: 'Full-stack web development notes.',
  themeConfig: {
    theme: 'vue',
    repo: '8483/notes',
    sidebar: [
      ['/', 'Introduction'],
      ['topics/algos', 'Algos'],
      ['topics/bash', 'Bash'],
      ['topics/dom', 'Dom'],
      ['topics/express', 'Express'],
      ['topics/mssql', 'Mssql'],
      ['topics/raspberrypi', 'Raspberrypi'],
      ['topics/testing', 'Testing'],
      ['topics/webpack', 'Webpack'],
      ['topics/ansible', 'Ansible'],
      ['topics/caching', 'Caching'],
      ['topics/electricity', 'Electricity'],
      ['topics/filesystem', 'Filesystem'],
      ['topics/mysql', 'Mysql'],
      ['topics/react', 'React'],
      ['topics/tmux', 'Tmux'],
      ['topics/architecture', 'Architecture'],
      ['topics/compression', 'Compression'],
      ['topics/electronics', 'Electronics'],
      ['topics/fp', 'Fp'],
      ['topics/networking', 'Networking'],
      ['topics/restful', 'Restful'],
      ['topics/users', 'Users'],
      ['topics/arduino', 'Arduino'],
      ['topics/config', 'Config'],
      ['topics/electron', 'Electron'],
      ['topics/git', 'Git'],
      ['topics/nginx', 'Nginx'],
      ['topics/rfid', 'Rfid'],
      ['topics/vagrant', 'Vagrant'],
      ['topics/async', 'Async'],
      ['topics/csharp', 'Csharp'],
      ['topics/elm', 'Elm'],
      ['topics/javascript', 'Javascript'],
      ['topics/nodemcu', 'Nodemcu'],
      ['topics/security', 'Security'],
      ['topics/vim', 'Vim'],
      ['topics/babel', 'Babel'],
      ['topics/css', 'Css'],
      ['topics/es6', 'Es6'],
      ['topics/linux', 'Linux'],
      ['topics/node', 'Node'],
      ['topics/ssh', 'Ssh'],
      ['topics/vm', 'Vm'],
      ['topics/base', 'Base'],
      ['topics/docker', 'Docker'],
      ['topics/excel', 'Excel'],
      ['topics/mobile', 'Mobile'],
      ['topics/oop', 'Oop'],
      ['topics/systemd', 'Systemd'],
      ['topics/vscode', 'Vscode'],
    ],
  },
};
